# Generated by Django 4.0.4 on 2022-05-15 09:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('OA', 'O`QUV ADABIYOTLAR'), ('V', 'VIDEODARSLAR'), ('P', 'TAQDIMOTLAR'), ('T', 'TEST')], max_length=5)),
                ('title', models.CharField(max_length=512, verbose_name='Mavzu')),
                ('content', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Statik sahifa',
                'verbose_name_plural': 'Statik sahifalar',
            },
        ),
    ]
