# Generated by Django 4.0.4 on 2022-05-15 10:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.CharField(choices=[('OA', 'O`QUV ADABIYOTLAR'), ('V', 'VIDEODARSLAR'), ('P', 'TAQDIMOTLAR'), ('T', 'TEST')], max_length=5, verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Kontent'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Holati'),
        ),
    ]
