# Generated by Django 4.0.4 on 2022-05-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_page_image_alter_page_category_alter_page_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Qisqacha mazmuni'),
        ),
    ]
