# Generated by Django 4.0.4 on 2022-10-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_page_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='position',
            field=models.IntegerField(default=1, verbose_name='Tartib raqami'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.CharField(choices=[('I', '1-BO’LIM. MAKTABGACHA TA’LIMDA BOLALARNI TABIAT BILAN TANISHTIRISHNING NAZARIY ASOSLARI VA TABIAT HAQIDA TUSHUNCHA'), ('II', '2-BO’LIM. MAKTABGACHA TA’LIM TASHKILOTLARIDA TABIATSHUNOSLIK ISHLARINI TASHKIL ETISH'), ('III', '3-BO’LIM. MAKTABGACHA TA’LIM TASHKILOTLARIDA TABIAT BILAN TANISHTIRISHNING MAZMUNI'), ('IV', '4-BO’LIM. MAKTABGACHA YOSHDAGI BOLALARNI TABIAT BILAN TANISHTIRISH METOD, VOSITALARI'), ('V', '5-BO’LIM. MAKTABGACHA YOSHDAGI BOLALARNING TABIAT BILAN TANISHTIRISHNING ISH SHAKLLARI'), ('VI', '6- BO’LIM. MAKTABGACHA TA’LIM TASHKILOTLARIDA TABIAT BURCHAGINI TASHKIL QILISH'), ('VII', '7- BO’LIM. YER MAYDONCHALARINI TASHKIL QILISH VA ULARNING TURLARI'), ('VIII', '8- BO’LIM. MAKTABGACHA TA’LIM MUASSASALARIDA TABIAT TANISHTIRISH ISHLARINI REJALASHTIRISH')], max_length=5),
        ),
    ]
